### ISSUE TITLE
ETA for this plugin

### ISSUE THREAD

**Issue by kevcodez** [EnlighterJS/Plugin.Gutenberg#1]
Hey there,

is there any ETA for this plugin? I am already using the Gutenberg Editor a lot and would love to see this plugin.

Is there anything I can help with to speed things up?

Greetings

**Comment by AndiDittrich** [comment]
Hi Kevin,

**there is no hard timeline/release date projected.**
It will be added to the next major Enlighter release but maybe not full-featured.

### Current State ###

There are still some unsolved issues like **inline highlighting** - i'm not sure if its possible to add this feature to the Gutenberg paragraph block because there seems to be no support for additional styles like in TinyMCE. i didn't checked the possibility for extending core blocks yet.

Additionally it takes a lot of time to reverse engineer the Gutenberg project...the docs are very "poor" ..

### Background ###
currently the Gutenberg Editor itself has [hundreds of unsolved issues](https://github.com/WordPress/gutenberg) and [some of them](https://github.com/EnlighterJS/Plugin.Gutenberg#current-limitations) affects the Enlighter.Gutenberg project itself. therefore i cannot recommended to use the Gutenberg Editor nor the Plugin for any kind of productive purpose.

if you like you can fix [8648](https://github.com/WordPress/gutenberg/issues/8648) and [8532](https://github.com/WordPress/gutenberg/issues/8532) ... :+1: 

best regards, Andi

**Comment by AndiDittrich** [comment]
current state:
![enlighterjs_gutenberg_test](https://user-images.githubusercontent.com/1474107/44336106-9f451100-a476-11e8-8f00-8811a4716ddf.png)

**Comment by AndiDittrich** [comment]
@kevcodez 

i've just released the [first version](https://github.com/EnlighterJS/Plugin.Gutenberg/releases/tag/v0.2.0) subjected for testing purpose. Block based highlighting is working fine

**I would be happy to receive feedback!**

best regards, Andi

**Comment by techrex** [comment]
I have added and enabled the plugin in my wordpress blog. However, no change happend in my blog's Gutenberg editor. I can't find any new block type. Do I miss something?
![image](https://user-images.githubusercontent.com/10336421/44461760-acaff600-a644-11e8-8833-d2fbb0cb3ea9.png)
![image](https://user-images.githubusercontent.com/10336421/44461779-c5b8a700-a644-11e8-835e-8ea55e200684.png)

**Comment by AndiDittrich** [comment]
@techrex 
did you upload the `dist/` directory including the plugin files ? they seem to be missing

**Required Structure**

```
wp-content/
   | - plugins/
   |      | -enlighter-gutenberg/
   |      |       |- enlighter-gutenberg.php
   |      |       |- dist/
   |      |       |      |- enlighterjs.gutenberg.min.css 
   |      |       |      |- enlighterjs.gutenberg.min.js
```

**Comment by AndiDittrich** [comment]
FYI: its added to the latest beta (3.8.0-BETA1) - https://github.com/EnlighterJS/Plugin.WordPress
