### ISSUE TITLE
Page fails to be saved when the code with "using" is written

### ISSUE THREAD

**Issue by kyrylomyr** [EnlighterJS/Plugin.Gutenberg#17]
How to reproduce:

Add the following code:
`using ()`

Language is C#, but it seems like it doesn't matter.
WP says that "Updating failed" when tries to save page.

**Comment by AndiDittrich** [comment]
Hi @kirmir ,

i'm unable to reproduce your issue. 

most similar issues (saving failed) are caused by some kind of web-security-solution which identifies your content (which is sent to the server) as possible attack and blocks the request (see browsers network tab within developer tools for details)

therefore, please try to reproduce your issue within another hosting environment without any kind of Web Application Firewall, IDPS or local "Antivirus" software - i assume that will work..

best regards, Andi

-----

used code which works as expected:


```
using ()

using (var font1 = new Font("Arial", 10.0f)) 
{
    byte charset = font1.GdiCharSet;
}
```
