### ISSUE TITLE
global linenumbers setting is ignored

### ISSUE THREAD

**Issue by atar-axis** [EnlighterJS/Plugin.Gutenberg#2]
Hey there!
Unfortunately the global linenumbers setting seems to be ignored - it is set to `ON` but the linenumbers are not shown until I activate it directly at the Gutenberg Block.

Cheers!

**Comment by AndiDittrich** [comment]
HI @atar-axis ,

please see https://github.com/EnlighterJS/Plugin.WordPress/issues/134#issuecomment-442451484

it's an issue with EnlighterJS v2 not the editor plugin itself - the Gutenberg Plugin is designed for EnlighterJS v3 - therefore it is still marked as beta.

The issue is caused by empty `data-enlighter-linenumbers` attribute which is interpreted as **false** by EnlighterJS v2 and **undefined** in EnlighterJS v3

best regards, Andi

**Comment by atar-axis** [comment]
Wonderful, thanks for you quick response!

**Comment by AndiDittrich** [comment]
i've changed the option parsing behaviour of EnlighterJS v2-legacy branch / [release v2.13.0](https://github.com/EnlighterJS/EnlighterJS/releases/tag/v2.13.0) as used by EnlighterJS v3 

it will become available in the Enlighter WordPress Plugin v3.9.0 (already available within the master branch)

**Comment by atar-axis** [comment]
Thanks Andi!
